### ISSUE TITLE
Could you please tell me how to reproduce the results referred in paper ?

### ISSUE THREAD

**Issue by zhgqcn** [UCA-Datalab/better_nilm#17]
Hello. Your work is really helpful for me. 
-  I run the code by following ` sh train_sequential.sh` and get some results.
![image](https://user-images.githubusercontent.com/44897668/209324930-137ed86c-625e-4e1b-a985-8fe0b05c8c3a.png)

- But the predict results are so bad(noisy) like this：
![image](https://user-images.githubusercontent.com/44897668/209324659-ae3043fe-4d7f-4d35-bbea-6ac5e782cc0a.png)

- So how to reproduce the result in the paper.
![image](https://user-images.githubusercontent.com/44897668/209324781-645028b6-c041-4e07-bde0-ce9ab4fdfbca.png)

- Thank you.

**Comment by zhgqcn** [comment]
![image](https://user-images.githubusercontent.com/44897668/209331833-a0f4c749-3e53-4cf6-bab4-f122f8c73d0c.png)

- When I debug the code, I find the the  y and s are dismatch.

**Comment by daniprec** [comment]
Hello @zhgqcn 

Excuse us for our late reply!
We are glad to know you are finding the repository useful. Unfortunately we are currently not working on it and are unable to help with your issue.
I hope your research is going well.
