### ISSUE TITLE
plot_output.py

### ISSUE THREAD

**Issue by RengarWang** [UCA-Datalab/better_nilm#4]
hi,i met a problem,

plot_output.py ,line 222 , in plot_weights 
model = path_input.rsplit('/', 1)[1]
IndexError: list index out of range

without classification weight ,F1 ,MAE chart,I hope to get your help，thank you.

**Comment by RengarWang** [comment]
Thanks，Problem solved, windows and Linux path issues！

**Comment by daniprec** [comment]
We will take this into account for future releases. Thanks for your contribution @RengarWang !
